services:
  web:
    build: .
    # Utilise le script d'entrée pour démarrer l'application
    entrypoint: ["sh", "docker-entrypoint.sh"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env