# Generated by Django 5.2.4 on 2025-07-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProtectedImage",
            fields=[
                (
                    "uuid",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("protected_image_path", models.CharField(max_length=255)),
                ("original_image_path", models.CharField(max_length=255)),
                (
                    "protection_strength",
                    models.DecimalField(decimal_places=2, max_digits=3),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("expiration_date", models.DateTimeField()),
            ],
        ),
    ]
