# Generated by Django 5.2.4 on 2025-07-24 14:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protection_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protectedimage',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
