# Generated by Django 5.2.4 on 2025-07-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protection_app', '0002_alter_protectedimage_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protectedimage',
            name='protection_strength',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
